// =============================================================================
// KivoAudioCoreCpp — contract_tests_main.cpp
// Contract Test Runner — Single entry point for all contract tests
// =============================================================================
//
// This file is the ONLY file with main().
// Each family test file exports a run_*_tests(ContractTestRunner&) function.
// No test logic is duplicated here.
// =============================================================================

#include "contract_tests_main.h"

// Family test runner declarations
void run_result_contract_tests(ContractTestRunner& runner);
void run_generation_id_contract_tests(ContractTestRunner& runner);
void run_sample_position_contract_tests(ContractTestRunner& runner);
void run_public_header_composability_tests(ContractTestRunner& runner);
void run_audio_format_descriptor_contract_tests(ContractTestRunner& runner);
void run_sample_format_contract_tests(ContractTestRunner& runner);
void run_channel_layout_contract_tests(ContractTestRunner& runner);
void run_frame_layout_contract_tests(ContractTestRunner& runner);
void run_channel_mask_contract_tests(ContractTestRunner& runner);
void run_dsd_rate_tests(ContractTestRunner& runner);
void run_native_dsd_format_tests(ContractTestRunner& runner);
void run_dop_marker_tests(ContractTestRunner& runner);
void run_dop_carrier_format_tests(ContractTestRunner& runner);
void run_native_decoded_format_contract_tests(ContractTestRunner& runner);
void run_core_canonical_format_contract_tests(ContractTestRunner& runner);
void run_render_format_contract_tests(ContractTestRunner& runner);
void run_device_format_contract_tests(ContractTestRunner& runner);
void run_format_negotiation_result_contract_tests(ContractTestRunner& runner);
void run_conversion_policy_contract_tests(ContractTestRunner& runner);
void run_resample_decision_contract_tests(ContractTestRunner& runner);
void run_bit_perfect_eligibility_contract_tests(ContractTestRunner& runner);
void run_negotiated_output_mode_contract_tests(ContractTestRunner& runner);
void run_clock_domain_contract_tests(ContractTestRunner& runner);
void run_seek_flush_contract_tests(ContractTestRunner& runner);
void run_device_clock_tests(ContractTestRunner& runner);
void run_stream_clock_tests(ContractTestRunner& runner);
void run_timeline_clock_tests(ContractTestRunner& runner);
void run_decoded_position_tests(ContractTestRunner& runner);
void run_rendered_position_tests(ContractTestRunner& runner);
void run_drift_estimate_tests(ContractTestRunner& runner);
void run_pause_resume_freeze_policy_tests(ContractTestRunner& runner);
void run_device_lost_position_report_rule_tests(ContractTestRunner& runner);
void run_seek_clock_reset_rule_tests(ContractTestRunner& runner);
void run_drain_eos_timeline_rule_tests(ContractTestRunner& runner);
void run_gapless_timeline_continuity_rule_tests(ContractTestRunner& runner);
void run_seek_intent_tests(ContractTestRunner& runner);
void run_seek_target_tests(ContractTestRunner& runner);
void run_seek_generation_tests(ContractTestRunner& runner);
void run_seek_anti_glitch_policy_tests(ContractTestRunner& runner);
void run_stale_frame_discard_rule_tests(ContractTestRunner& runner);
void run_output_truth_snapshot_tests(ContractTestRunner& runner);
void run_bitperfect_truth_report_tests(ContractTestRunner& runner);
void run_bitperfect_rejection_reason_tests(ContractTestRunner& runner);
void run_processing_participation_tests(ContractTestRunner& runner);
void run_device_format_match_tests(ContractTestRunner& runner);
void run_sample_transparency_tests(ContractTestRunner& runner);
void run_host_audio_engine_participation_tests(ContractTestRunner& runner);
void run_output_path_truth_tests(ContractTestRunner& runner);
void run_output_policy_decision_tests(ContractTestRunner& runner);
void run_output_policy_explanation_tests(ContractTestRunner& runner);
void run_realtime_path_contract_tests(ContractTestRunner& runner);
void run_realtime_prohibition_contract_tests(ContractTestRunner& runner);
void run_realtime_ownership_contract_tests(ContractTestRunner& runner);
void run_realtime_buffer_contract_tests(ContractTestRunner& runner);
void run_realtime_transport_contract_tests(ContractTestRunner& runner);
void run_realtime_boundary_contract_tests(ContractTestRunner& runner);
void run_generation_identity_tests(ContractTestRunner& runner);
void run_generation_comparison_tests(ContractTestRunner& runner);
void run_generation_classification_tests(ContractTestRunner& runner);
void run_generation_advance_tests(ContractTestRunner& runner);
void run_buffer_identity_tests(ContractTestRunner& runner);
void run_buffer_ownership_tests(ContractTestRunner& runner);
void run_buffer_lifetime_tests(ContractTestRunner& runner);
void run_buffer_reference_tests(ContractTestRunner& runner);
void run_buffer_share_tests(ContractTestRunner& runner);
void run_queue_capacity_tests(ContractTestRunner& runner);
void run_queue_slot_tests(ContractTestRunner& runner);
void run_queue_staleness_tests(ContractTestRunner& runner);
void run_queue_boundary_tests(ContractTestRunner& runner);
void run_source_identity_tests(ContractTestRunner& runner);
void run_source_location_tests(ContractTestRunner& runner);
void run_source_access_tests(ContractTestRunner& runner);
void run_source_reader_tests(ContractTestRunner& runner);
void run_source_container_tests(ContractTestRunner& runner);
void run_source_boundary_tests(ContractTestRunner& runner);
void run_source_outcome_tests(ContractTestRunner& runner);
void run_cue_boundary_tests(ContractTestRunner& runner);
void run_cue_range_tests(ContractTestRunner& runner);
void run_cue_continuity_tests(ContractTestRunner& runner);
void run_error_domain_tests(ContractTestRunner& runner);
void run_error_domain_category_tests(ContractTestRunner& runner);
void run_error_severity_tests(ContractTestRunner& runner);
void run_error_attributes_tests(ContractTestRunner& runner);
void run_recovery_action_tests(ContractTestRunner& runner);
void run_recovery_matrix_tests(ContractTestRunner& runner);
void run_error_outcome_tests(ContractTestRunner& runner);
void run_state_phase_tests(ContractTestRunner& runner);
void run_state_transition_tests(ContractTestRunner& runner);
void run_state_rejection_tests(ContractTestRunner& runner);
void run_state_rule_tests(ContractTestRunner& runner);
void run_state_scenario_tests(ContractTestRunner& runner);
void run_state_machine_contract_tests(ContractTestRunner& runner);
void run_command_identity_tests(ContractTestRunner& runner);
void run_command_kind_tests(ContractTestRunner& runner);
void run_command_ordering_tests(ContractTestRunner& runner);
void run_command_decision_tests(ContractTestRunner& runner);
void run_command_scenario_tests(ContractTestRunner& runner);
void run_command_semantics_contract_tests(ContractTestRunner& runner);
void run_observability_event_tests(ContractTestRunner& runner);
void run_observability_metric_tests(ContractTestRunner& runner);
void run_observability_trace_tests(ContractTestRunner& runner);
void run_observability_diagnostic_tests(ContractTestRunner& runner);
void run_observability_contract_tests(ContractTestRunner& runner);
void run_privacy_policy_tests(ContractTestRunner& runner);
void run_distribution_policy_tests(ContractTestRunner& runner);
void run_audio_core_policy_contract_tests(ContractTestRunner& runner);

// =============================================================================
// Main
// =============================================================================
int main() {
    std::cout << "=== Contract Tests ===\n\n";

    ContractTestRunner runner;

    run_result_contract_tests(runner);
    run_generation_id_contract_tests(runner);
    run_sample_position_contract_tests(runner);
    run_public_header_composability_tests(runner);
    run_audio_format_descriptor_contract_tests(runner);
    run_sample_format_contract_tests(runner);
    run_channel_layout_contract_tests(runner);
    run_frame_layout_contract_tests(runner);
    run_channel_mask_contract_tests(runner);
    run_dsd_rate_tests(runner);
    run_native_dsd_format_tests(runner);
    run_dop_marker_tests(runner);
    run_dop_carrier_format_tests(runner);
    run_native_decoded_format_contract_tests(runner);
    run_core_canonical_format_contract_tests(runner);
    run_render_format_contract_tests(runner);
    run_device_format_contract_tests(runner);
    run_format_negotiation_result_contract_tests(runner);
    run_conversion_policy_contract_tests(runner);
    run_resample_decision_contract_tests(runner);
    run_bit_perfect_eligibility_contract_tests(runner);
    run_negotiated_output_mode_contract_tests(runner);
    run_clock_domain_contract_tests(runner);
    run_seek_flush_contract_tests(runner);
    run_device_clock_tests(runner);
    run_stream_clock_tests(runner);
    run_timeline_clock_tests(runner);
    run_decoded_position_tests(runner);
    run_rendered_position_tests(runner);
    run_drift_estimate_tests(runner);
    run_pause_resume_freeze_policy_tests(runner);
    run_device_lost_position_report_rule_tests(runner);
    run_seek_clock_reset_rule_tests(runner);
    run_drain_eos_timeline_rule_tests(runner);
    run_gapless_timeline_continuity_rule_tests(runner);
    run_seek_intent_tests(runner);
    run_seek_target_tests(runner);
    run_seek_generation_tests(runner);
    run_seek_anti_glitch_policy_tests(runner);
    run_stale_frame_discard_rule_tests(runner);
    run_output_truth_snapshot_tests(runner);
    run_bitperfect_truth_report_tests(runner);
    run_bitperfect_rejection_reason_tests(runner);
    run_processing_participation_tests(runner);
    run_device_format_match_tests(runner);
    run_sample_transparency_tests(runner);
    run_host_audio_engine_participation_tests(runner);
    run_output_path_truth_tests(runner);
    run_output_policy_decision_tests(runner);
    run_output_policy_explanation_tests(runner);
    run_realtime_path_contract_tests(runner);
    run_realtime_prohibition_contract_tests(runner);
    run_realtime_ownership_contract_tests(runner);
    run_realtime_buffer_contract_tests(runner);
    run_realtime_transport_contract_tests(runner);
    run_realtime_boundary_contract_tests(runner);
    run_generation_identity_tests(runner);
    run_generation_comparison_tests(runner);
    run_generation_classification_tests(runner);
    run_generation_advance_tests(runner);
    run_buffer_identity_tests(runner);
    run_buffer_ownership_tests(runner);
    run_buffer_lifetime_tests(runner);
    run_buffer_reference_tests(runner);
    run_buffer_share_tests(runner);
    run_queue_capacity_tests(runner);
    run_queue_slot_tests(runner);
    run_queue_staleness_tests(runner);
    run_queue_boundary_tests(runner);
    run_source_identity_tests(runner);
    run_source_location_tests(runner);
    run_source_access_tests(runner);
    run_source_reader_tests(runner);
    run_source_container_tests(runner);
    run_source_boundary_tests(runner);
    run_source_outcome_tests(runner);
    run_cue_boundary_tests(runner);
    run_cue_range_tests(runner);
    run_cue_continuity_tests(runner);
    run_error_domain_tests(runner);
    run_error_domain_category_tests(runner);
    run_error_severity_tests(runner);
    run_error_attributes_tests(runner);
    run_recovery_action_tests(runner);
    run_recovery_matrix_tests(runner);
    run_error_outcome_tests(runner);
    run_state_phase_tests(runner);
    run_state_transition_tests(runner);
    run_state_rejection_tests(runner);
    run_state_rule_tests(runner);
    run_state_scenario_tests(runner);
    run_state_machine_contract_tests(runner);
    run_command_identity_tests(runner);
    run_command_kind_tests(runner);
    run_command_ordering_tests(runner);
    run_command_decision_tests(runner);
    run_command_scenario_tests(runner);
    run_command_semantics_contract_tests(runner);
    run_observability_event_tests(runner);
    run_observability_metric_tests(runner);
    run_observability_trace_tests(runner);
    run_observability_diagnostic_tests(runner);
    run_observability_contract_tests(runner);
    run_privacy_policy_tests(runner);
    run_distribution_policy_tests(runner);
    run_audio_core_policy_contract_tests(runner);

    std::cout << "=== " << runner.tests_passed << "/" << runner.tests_run << " passed ===\n";
    return runner.exit_code();
}
